### ISSUE TITLE
Question — Gamma

### ISSUE THREAD

**Issue by partlyhuman** [dekkit/RGB-to-Component-Transcoder#4]
Hi there! Thank you for sharing this design! I just built one of the V03A revisions, and I'm trying it out with an unmodified Genesis 2 (NTSC, VA1 revision). The colors look like maybe the gamma is way off, I'm wondering if you have any inkling what the issue could be. Comparing transcoded YPbPr first and composite for reference second:
![IMG_2625](https://user-images.githubusercontent.com/327136/125892744-d0c5624e-faf0-4ab7-9eba-f2f36a854598.jpeg)
![IMG_2627](https://user-images.githubusercontent.com/327136/125892754-26330dde-8e9d-44f1-a11b-f0a0a8efb343.jpeg)
![IMG_2626](https://user-images.githubusercontent.com/327136/125892791-cda7cdd0-2397-45b1-b3e7-d1c1ad8ee0ca.jpeg)
![IMG_2615](https://user-images.githubusercontent.com/327136/125892796-34bd7869-3b3d-411f-87a9-de0ddc95c2de.jpeg)

One deviation from the design is I've used electrolytic instead of ceramic caps for the 1uF caps, placing them in the correct orientation (negative legs toward ground plate in the obvious cases, and as measured in the circuit via multimeter in other cases—turns out to be negative facing down or right in the V03a layout with the exception of the actual electrolytic cap C5).

I'll likely try building another from the ground up and see if I get the same results, but if you have any ideas for something to try, I would be happy to hear your thoughts. Thank you again! (Update: Built a second one and have the same result.)

**Comment by partlyhuman** [comment]
This output colorspace may be specific to the Genesis. Used together with my RGB-modded PC Engine Duo, the results were terrific.  I've published a project box customized for the transcoder here https://www.thingiverse.com/thing:4912451

Thank you again for making your designs public!

**Comment by dekkit** [comment]
Sorry for the delay in reply and thank you for sharing your 3d printable box design!

A few ideas, given it works for the duo, id check your cable for the genesis 2.  Ie make sure youre getting clean RGB signals (there may also be regional differences in pal vs ntsc scart cables).

Visually it looks like 'Green' input is under powered, likely on the input side from your pics.

Also check what you are feeding in for sync as that could be a considerarion (unlikely).

Color issues can also be result of the THS amp pins not making a solid connection with pads (tho unlikely given it works for another console)

Glad you were able to use, it was a great learning experience.
